const fs = require('fs');
const path = 'D:/FOLLOWUP/Carga_turnos/CARGA_DE_TURNOS.html';
let text = fs.readFileSync(path, 'utf8');

const exactReplacements = [
  ['<tr>\r\n                  <td data-label="Semana">02-02-2025</td>', '<tr data-detail-generation-row data-detail-store="Arequipa" data-detail-week="02-02-2025">\r\n                  <td data-label="Semana">02-02-2025</td>'],
  ['<tr>\r\n                  <td data-label="Semana">09-02-2025</td>', '<tr data-detail-generation-row data-detail-store="Arequipa" data-detail-week="09-02-2025">\r\n                  <td data-label="Semana">09-02-2025</td>'],
  ['<tr>\r\n                  <td data-label="Semana">16-02-2025</td>', '<tr data-detail-generation-row data-detail-store="Arequipa" data-detail-week="16-02-2025">\r\n                  <td data-label="Semana">16-02-2025</td>'],
  ['<tr>\r\n                  <td data-label="Semana">23-02-2025</td>', '<tr data-detail-generation-row data-detail-store="Arequipa" data-detail-week="23-02-2025">\r\n                  <td data-label="Semana">23-02-2025</td>'],
  ['<tr>\r\n                  <td data-label="Semana">02-03-2025</td>', '<tr data-detail-generation-row data-detail-store="Arequipa" data-detail-week="02-03-2025">\r\n                  <td data-label="Semana">02-03-2025</td>'],
  ['<button class="detail-square-button edit" type="button" aria-label="Editar"><span class="material-symbols-outlined">edit</span></button>', '<button class="detail-square-button edit" type="button" aria-label="Editar" data-open-generation-edit><span class="material-symbols-outlined">edit</span></button>']
];
for (const [from, to] of exactReplacements) {
  text = text.replace(from, to);
}

const stateBlock = `    const generationSelectedVendorsByMode = {\r\n      "meta-justa": [],\r\n      asistencia: [],\r\n    };\r\n`;
if (!text.includes('const generationEditPresets = {')) {
  text = text.replace(stateBlock, `${stateBlock}    const generationEditPresets = {\r\n      "02-02-2025": {\r\n        selectedVendors: ["Javier Soto Pérez", "Viviana Núñez Toledo", "Juan Carrasco Soto"],\r\n        assignmentsByMode: {\r\n          "meta-justa": {\r\n            "Javier Soto Pérez": { 0: "morning", 1: "afternoon", 2: "fullday", 3: "afternoon", 4: "off", 5: "off", 6: "morning" },\r\n            "Viviana Núñez Toledo": { 0: "afternoon", 1: "morning", 2: "afternoon", 3: "fullday", 4: "morning", 5: "off", 6: "off" },\r\n            "Juan Carrasco Soto": { 0: "fullday", 1: "afternoon", 2: "morning", 3: "afternoon", 4: "fullday", 5: "off", 6: "off" }\r\n          },\r\n          asistencia: {}\r\n        }\r\n      }\r\n    };\r\n`);
}

const contextBlock = `    const setGenerationContext = ({ store, week }) => {\r\n      const safeStore = store || detailStoreName?.textContent || "Arequipa";\r\n      const safeWeek = week || reportingWeeks[0];\r\n\r\n      if (generationStoreLabel) generationStoreLabel.textContent = safeStore;\r\n      if (generationWeekLabel) generationWeekLabel.textContent = safeWeek;\r\n      renderGenerationWeekOptions?.(safeWeek);\r\n      if (generationBreadcrumbStore) generationBreadcrumbStore.textContent = \`Turnos \${safeStore}\`;\r\n      renderGenerationStoreOptions?.(generationStoreSearch?.value || "");\r\n    };\r\n`;
if (!text.includes('const openGenerationScreen = ({ store, week, presetWeek = "" } = {}) => {')) {
  text = text.replace(contextBlock, `${contextBlock}\r\n    const cloneGenerationAssignments = (assignments = {}) => Object.fromEntries(\r\n      Object.entries(assignments).map(([vendorName, days]) => [vendorName, { ...days }])\r\n    );\r\n\r\n    const loadGenerationEditPreset = (week) => {\r\n      const preset = generationEditPresets[week];\r\n      if (!preset) return false;\r\n\r\n      generationSelectedVendorsByMode["meta-justa"] = [...(preset.selectedVendors || [])];\r\n      generationSelectedVendorsByMode.asistencia = [...(preset.selectedVendorsAsistencia || [])];\r\n      generationAssignmentsByMode["meta-justa"] = cloneGenerationAssignments(preset.assignmentsByMode?.["meta-justa"] || {});\r\n      generationAssignmentsByMode.asistencia = cloneGenerationAssignments(preset.assignmentsByMode?.asistencia || {});\r\n      syncGenerationVendorSelection(activeGenerationMode);\r\n      renderGenerationBoard(activeGenerationMode);\r\n      return true;\r\n    };\r\n\r\n    const openGenerationScreen = ({ store, week, presetWeek = "" } = {}) => {\r\n      setActiveScreen("generation");\r\n      setGenerationContext({ store, week });\r\n      closeGenerationAssignMenu();\r\n      closeGenerationSaveAlert();\r\n      if (presetWeek) {\r\n        loadGenerationEditPreset(presetWeek);\r\n      } else {\r\n        syncGenerationVendorSelection(activeGenerationMode);\r\n        renderGenerationBoard(activeGenerationMode);\r\n      }\r\n    };\r\n`);
}

const navBlock = `    generationButtons.forEach((button) => {\r\n      button.addEventListener("click", () => {\r\n        const row = button.closest("tr");\r\n        const weekCell = row?.querySelector('[data-label="Semana"]');\r\n        const week = weekCell?.textContent?.trim() || row?.children?.[0]?.textContent?.trim() || reportingWeeks[0];\r\n        const store = detailStoreName?.textContent?.trim() || "Arequipa";\r\n        setGenerationContext({ store, week });\r\n        setActiveScreen("generation");\r\n      });\r\n    });\r\n`;
const navReplacement = `    generationButtons.forEach((button) => {\r\n      button.addEventListener("click", () => {\r\n        const row = button.closest("tr");\r\n        const weekCell = row?.querySelector('[data-label="Semana"]');\r\n        const week = weekCell?.textContent?.trim() || row?.children?.[0]?.textContent?.trim() || reportingWeeks[0];\r\n        const store = detailStoreName?.textContent?.trim() || "Arequipa";\r\n        openGenerationScreen({ store, week });\r\n      });\r\n    });\r\n\r\n    document.querySelectorAll("[data-open-generation-edit]").forEach((button) => {\r\n      button.addEventListener("click", () => {\r\n        const row = button.closest("[data-detail-generation-row]");\r\n        if (!row) return;\r\n        openGenerationScreen({\r\n          store: row.dataset.detailStore || detailStoreName?.textContent?.trim() || "Arequipa",\r\n          week: row.dataset.detailWeek || reportingWeeks[0],\r\n          presetWeek: row.dataset.detailWeek || ""\r\n        });\r\n      });\r\n    });\r\n`;
text = text.replace(navBlock, navReplacement);

fs.writeFileSync(path, text, 'utf8');
