const fs = require('fs');
const path = 'D:/FOLLOWUP/Carga_turnos/CARGA_DE_TURNOS.html';
let content = fs.readFileSync(path, 'utf8');

if (!content.includes('<div class="generation-category-modal"')) {
  const modalLines = [
    '',
    '  <div class="generation-category-modal" data-generation-category-modal hidden>',
    '    <div class="generation-category-modal-backdrop" data-generation-category-close></div>',
    '    <section class="generation-category-modal-dialog" role="dialog" aria-modal="true" aria-labelledby="generation-category-title">',
    '      <header class="generation-category-modal-head">',
    '        <h2 id="generation-category-title">Nueva Categoría de Turno</h2>',
    '        <p>Crea una nueva categoría para organizar turnos que usarás con frecuencia.</p>',
    '      </header>',
    '',
    '      <div class="generation-category-modal-body">',
    '        <label class="generation-category-field">',
    '          <span>Nombre de la Categoría <strong>*</strong></span>',
    '          <input type="text" placeholder="Ej. Turnos de Santiago" data-generation-category-name />',
    '        </label>',
    '',
    '        <label class="generation-category-field">',
    '          <span>Descripción (opcional)</span>',
    '          <textarea rows="4" placeholder="Ej. Turnos predefinidos para tiendas ubicadas en Santiago de Chile." data-generation-category-description></textarea>',
    '        </label>',
    '',
    '        <p class="generation-category-helper">Agrega detalles que ayuden a identificar cuándo usar esta categoría.</p>',
    '      </div>',
    '',
    '      <footer class="generation-category-modal-actions">',
    '        <button class="secondary-button generation-category-cancel" type="button" data-generation-category-close>Cancelar</button>',
    '        <button class="primary-button generation-category-submit" type="button" data-generation-category-submit>Crear Categoría</button>',
    '      </footer>',
    '    </section>',
    '  </div>'
  ];
  content = content.replace('\r\n  <script>', '\r\n' + modalLines.join('\r\n') + '\r\n  <script>');
}

content = content.replace('Sin descripci?n', 'Sin descripción');
content = content.replace(
  '    const resetGenerationCreateForm = () => {\n      generationEditingShiftId = null;\n      generationCreateState = { isOff: false, includesLunch: true, color: "teal" };',
  '    const resetGenerationCreateForm = () => {\n      generationEditingShiftId = null;\n      generationModalContext = { surface: "main", card: null, isEditing: false };\n      generationCreateState = { isOff: false, includesLunch: true, color: "teal" };'
);

const replacement = [
'    const saveGenerationShift = () => {',
'      const shiftName = generationCreateNameInput?.value.trim();',
'      if (!shiftName) {',
'        generationCreateNameInput?.focus();',
'        return;',
'      }',
'      const toneConfig = generationCustomShiftTones[generationCreateState.color] || generationCustomShiftTones.teal;',
'      const startTime = generationCreateStartInput?.value || "08:00";',
'      const endTime = generationCreateEndInput?.value || "14:00";',
'      const lunchStart = generationCreateLunchStartInput?.value || "12:00";',
'      const lunchEnd = generationCreateLunchEndInput?.value || "13:00";',
'      const schedule = generationCreateState.isOff ? "Sin turno" : `${startTime} - ${endTime}`;',
'      const shiftPayload = {',
'        title: shiftName,',
'        schedule,',
'        tone: toneConfig.board,',
'        color: generationCreateState.color,',
'        isOff: generationCreateState.isOff,',
'        includesLunch: generationCreateState.includesLunch,',
'        startTime,',
'        endTime,',
'        lunchStart,',
'        lunchEnd',
'      };',
'',
'      if (generationModalContext.surface === "config" && generationModalContext.card) {',
'        applyConfigShiftCard(generationModalContext.card, shiftPayload);',
'        closeGenerationCreateModal();',
'        return;',
'      }',
'',
'      if (generationEditingShiftId) {',
'        const existingShift = generationShiftOptions.find((option) => option.id === generationEditingShiftId);',
'        if (!existingShift) return;',
'        Object.assign(existingShift, shiftPayload);',
'      } else {',
'        if (generationShiftOptions.length >= GENERATION_SHIFT_LIMIT) {',
'          closeGenerationCreateModal();',
'          return;',
'        }',
'        generationShiftOptions.push({',
'          id: `custom-${Date.now()}` ,',
'          ...shiftPayload',
'        });',
'      }',
'',
'      renderGenerationShiftPills();',
'      renderGenerationAssignMenu();',
'      renderGenerationBoard();',
'      closeGenerationCreateModal();',
'    };',
'',
'    const deleteGenerationShift = () => {',
'      if (generationModalContext.surface === "config" && generationModalContext.card) {',
'        resetConfigShiftCardToAvailable(generationModalContext.card);',
'        closeGenerationCreateModal();',
'        return;',
'      }',
'',
'      if (!generationEditingShiftId) return;',
'      const shiftIndex = generationShiftOptions.findIndex((option) => option.id === generationEditingShiftId);',
'      if (shiftIndex < 0) return;',
'',
'      generationShiftOptions.splice(shiftIndex, 1);',
'      Object.values(generationAssignmentsByMode).forEach((assignments) => {',
'        Object.keys(assignments).forEach((key) => {',
'          if (assignments[key] === generationEditingShiftId) {',
'            delete assignments[key];',
'          }',
'        });',
'      });',
'',
'      renderGenerationShiftPills();',
'      renderGenerationAssignMenu();',
'      renderGenerationBoard();',
'      closeGenerationCreateModal();',
'    };',
'',
'    const createGenerationCategory = () => {',
'      const categoryName = generationCategoryNameInput?.value.trim();',
'      const categoryDescription = generationCategoryDescriptionInput?.value.trim() || "";',
'      if (!categoryName) {',
'        generationCategoryNameInput?.focus();',
'        return;',
'      }',
'      if (!generationConfigTableBody) return;',
'',
'      generationConfigTableBody.insertAdjacentHTML("beforeend", buildGenerationConfigCategoryRow(categoryName, categoryDescription));',
'      closeGenerationCategoryModal();',
'    };',
'',
'    const closeGenerationAssignMenu = () => {'
].join('\n');

content = content.replace(/    const saveGenerationShift = \(\) => \{[\s\S]*?    const closeGenerationAssignMenu = \(\) => \{/, replacement);
content = content.replace('id: `custom-${Date.now()}` ,', 'id: `custom-${Date.now()}`,' );

fs.writeFileSync(path, content, 'utf8');
